### ISSUE TITLE
Feature request: Go to website via url scheme myproxy.com/goto/blockeddomain.com

### ISSUE THREAD

**Issue by tuananh** [madhurjain/gopee#5]
I would like to add a feature which i can go to a website through proxy like myproxy.com/goto/blockeddomain.com.

I don't have any experience with Go. Please help me save sometimes pointing to where I should read. I don't want to learn Go just for this purpose :dancer: It's probably just modify a bit and redirect to /p proxy handler i guess.

**Comment by madhurjain** [comment]
You can already do something similar

https://gopee.herokuapp.com?url=google.com

**Comment by tuananh** [comment]
@madhurjain thanks. i didnt know abt this.
