### ISSUE TITLE
allowed urls for post/ajax/cookie

### ISSUE THREAD

**Issue by snapo** [madhurjain/gopee#8]
Hi instead of not implementig it, or block it to prevent abusing the service, would it not be possible to allow cookies/ajax/post request only from specific urls?

*.google.com
*.facebook.com
*.twitter.com
*.microsoft.com
....

That would still allow users to connect to the sites and post something in restricted networks.

**Comment by madhurjain** [comment]
@snapo I plan to implement these very soon. Stuck with another upcoming project.

**Comment by chinmoyden** [comment]
@madhurjain Are you still working on supporting ajax requests?

**Comment by madhurjain** [comment]
@chinmoyden I did start working on it, but last month was very busy, will try to push through it next week

**Comment by chinmoyden** [comment]
@madhurjain Thanks. GoPee can be a very useful tool to bypass restrictive networks and online censorship.  I think once ajax and session cookie is supported and more people start using this, you'll see people start contributing code.

**Comment by madhurjain** [comment]
@snapo @chinmoyden AJAX support added. Could you please check and give me a feedback ?

http://go-gopee.rhcloud.com/

**Comment by snapo** [comment]
Hi and sorry, didnt had time yet to test... will test for sure tomorrow friday...
Thank you already for the big update. Is there anything i could help you with?
