### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by chinmoyden** [madhurjain/gopee#9]
Hello,

After the recent updates, I can't deploy GoPee on my servers anymore. I've tried on Ubuntu, Debian and CentOS servers. I get the same error everywhere. 
```
[root@owl gopee]# go run gopee.go
# command-line-arguments
./gopee.go:55: undefined: Manager
./gopee.go:303: undefined: NewManager
```

**Comment by madhurjain** [comment]
@chinmoyden It isn't a single file anymore due to added support for sessions and cookies. You must build it first with `go build` and then run the binary `./gopee`

Will update the README
